#!/bin/bash

tmp0=$(mktemp)
tmp1=$(mktemp)
echo '{}' > $tmp0

jq '.parsed.count = 1 | .parsed.operators = ["=",":","~",">"]' $tmp0 > $tmp1
jq '.parsed.parameter.name.aliases = "alias1, alias2"' $tmp1 > $tmp0
jq '.parsed.parameter.name.type = "string"' $tmp0 > $tmp1
jq '.parsed.parameter.name.default = "default value"' $tmp1 > $tmp0
jq '.parsed.parameter.name.operator = ">="' $tmp0 > $tmp1
jq '.parsed.parameter.name.value = "[val1, val2, val3]"' $tmp1
